_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide

  positionss:
    - bg-pos-t: Top
    - bg-pos-b: Bottom
    - bg-pos-l: Left Center
    - bg-pos-r: Right Center
    - bg-pos-c: Center

  column-sizes:
    - col-3: 1/4
    - col-4: 1/3
    - col-6: 1/2
    - col-12: Full width
    - col-3_xs-6: 1/4 (1/2 mobile)
    - col-3_xs-12: 1/4 (full width mobile)
    - col-4_xs-6: 1/3 (1/2 mobile)
    - col-4_xs-12: 1/3 (full width mobile)
    - col-6_xs-12: 1/2 (full width mobile)
